### ISSUE TITLE
is_dark_rgb comparison value seems wrong

### ISSUE THREAD

**Issue by ulope** [rocky/shell-term-background#2]
(Unfortunately I've so far only been able to test this on one terminal)

It looks to me that the comparison value used in the `is_dark_rgb` function is wrong.

The RGB values returned from my terminal (iTerm2) are all between `0x00` and `0xff`  and therefore `R+B+G` is always smaller then `(.6 * (0xffff * 3))` leading to the script always reporting dark mode.

**Comment by rocky** [comment]
A real xterm allows R, G, or B values up to 0xffff. xterm-256color seems to allow only up to 0xff.

Try the code in branch  [TERMINAL_COLOR_MIDPOINT](https://github.com/rocky/bash-term-background/tree/TERMINAL_COLOR_MIDPOINT). If that works, I'll push that to the master branch.
